# Generated by Django 5.0.6 on 2024-06-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='release_date',
            new_name='data_de_lançamento',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='developer',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='title',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
    ]
